server:
  port: 7777
  context-path: /scala-boot

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/imooc-boot-scala
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
